Dont run cocotb tests

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -34,25 +34,25 @@ jobs:
       - name: run Chisel tests
         run: sbt test
 
-      - name: Run tests
-        run: |
-          cd test
-          make clean
-          make
-          # make will return success even if the test fails, so check for failure in the results.xml
-          ! grep failure results.xml
-
-      - name: Test Summary
-        uses: test-summary/action@v2.3
-        with:
-          paths: "test/results.xml"
-        if: always()
-
-      - name: upload vcd
-        if: success() || failure()
-        uses: actions/upload-artifact@v4
-        with:
-          name: test-vcd
-          path: |
-            test/tb.vcd
-            test/result.xml
+#      - name: Run tests
+#        run: |
+#          cd test
+#          make clean
+#          make
+#          # make will return success even if the test fails, so check for failure in the results.xml
+#          ! grep failure results.xml
+#
+#      - name: Test Summary
+#        uses: test-summary/action@v2.3
+#        with:
+#          paths: "test/results.xml"
+#        if: always()
+#
+#      - name: upload vcd
+#        if: success() || failure()
+#        uses: actions/upload-artifact@v4
+#        with:
+#          name: test-vcd
+#          path: |
+#            test/tb.vcd
+#            test/result.xml
